### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by skariyadan** [skariyadan/InnReservationSystem#1]
- [ ] ### **GENERAL**

- [ ] write README (how to compile and run, names etc)

- [ ] (possibly) write MAKEFILE

- [ ] on startup check if tables already exist, create with command

- [ ] on startup check if table is empty or not

- [ ] just a general overview look over to make sure UI/DBMS is good

- [ ] check our tables

- [ ] package and submit

- [ ] ### **ADMIN**

- [ ] current status display

- [ ] table display

- [ ] clear database

- [ ] load/reload database

- [ ] database removal

- [ ] switch subsystem

- [ ] ### **Owner**

- [ ] occupancy overview

- [ ] revenue

- [ ] reservations

- [ ] rooms

- [ ] detailed reservation information

- [ ] ### **Guest**

- [ ] rooms/rates

- [ ] checking room availability

- [ ] pricing

- [ ] reservations

- [ ] completing a reservation

- [ ] updating the database
